server:
  port: 9090

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/employeemanagement
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
